# Generated by Django 4.1.1 on 2022-11-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondownership',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
