# Generated by Django 4.1.1 on 2022-11-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_forum', '0003_bondtransaction_value_propertytransaction_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondownership',
            name='value',
        ),
        migrations.RemoveField(
            model_name='propertyownership',
            name='value',
        ),
    ]
