# Generated by Django 4.1.1 on 2022-11-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_forum', '0005_delta_stockquery_propertyquery_bondquery_agentquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(default='None', max_length=100)),
                ('rate', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
